<style>
    .quickview-button-container {
        text-align: center;
    }
    .quickview-button-container .quickview-button, .quickview-minicart-button {
        width: 100%;
        height: 50px;
    }
</style>
<div class="quickview-button-container">
    <button class="action quickview-minicart-button primary" data-mage-init='{"Fr3on_QuickView/js/quickview_minicart": {}}'>
        Quick View
    </button>
</div>
